site_name: dotnet-6502
site_description: 6502 CPU emulator and Commodore 64 and other system implementations in .NET
site_author: Highbyte
site_url: https://highbyte.github.io/dotnet-6502/docs/
repo_url: https://github.com/highbyte/dotnet-6502
repo_name: highbyte/dotnet-6502
edit_uri: edit/master/docs/
docs_dir: docs

validation:
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn
    anchors: warn
  nav:
    omitted_files: warn
    not_found: warn

theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: custom
    accent: custom
  font:
    text: Fira Code
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.path
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
  logo: assets/logo-simple-128.png
  favicon: assets/logo-simple-128.png
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/github-prerelease.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - includes
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/highbyte/dotnet-6502

nav:
  - Home:
      - Overview: index.md
      - Limitations: home/limitations.md
      - Development: home/development.md
      - References: home/references.md
  - Architecture: architecture.md
  - Web apps:
      - Overview: web-apps/overview.md
      - Avalonia Browser app: web-apps/avalonia-browser.md
      - Blazor Web Assembly app: web-apps/blazor-wasm.md
  - Desktop apps:
      - Overview: desktop-apps/overview.md
      - Installation: desktop-apps/installation.md
      - Avalonia Desktop: 
        - App: desktop-apps/avalonia-desktop.md
        - Automation: desktop-apps/avalonia-desktop-automation.md
        - Troubleshooting: desktop-apps/avalonia-desktop-troubleshooting.md
      - SadConsole: 
        - App: desktop-apps/sadconsole.md
        - Troubleshooting: desktop-apps/sadconsole-troubleshooting.md
      - SilkNetNative: 
        - App: desktop-apps/silknet-native.md
        - Troubleshooting: desktop-apps/silknet-native-troubleshooting.md
      - Console Monitor: 
        - App: desktop-apps/console-monitor.md
      - Headless:
        - App: desktop-apps/headless.md
  - Libraries:
      - Overview: libraries/overview.md
      - Core libraries:
          - Overview: libraries/core/overview.md
          - CPU: libraries/core/dotnet6502.md
          - Systems: libraries/core/dotnet6502-systems.md
          - Systems.Plugins: libraries/core/dotnet6502-systems-plugins.md
          - DebugAdapter: libraries/core/dotnet6502-debugadapter.md
          - Monitor: libraries/core/dotnet6502-monitor.md
          - Remoting: libraries/core/dotnet6502-remoting.md
          - Scripting.MoonSharp: libraries/core/dotnet6502-scripting-moonsharp.md
          - AI: libraries/core/dotnet6502-ai.md
      - System-specific core libraries:
          - C64: libraries/system-specific/c64.md
          - Generic: libraries/system-specific/generic.md
          - VIC-20: libraries/system-specific/vic20.md
      - Implementation libraries:
          - Overview: libraries/implementation/overview.md
          - AspNet: libraries/implementation/aspnet.md
          - Avalonia: libraries/implementation/avalonia.md
          - Browser: libraries/implementation/browser.md
          - NAudio: libraries/implementation/naudio.md
          - SadConsole: libraries/implementation/sadconsole.md
          - SilkNet: libraries/implementation/silknet.md
          - SilkNet.SDL: libraries/implementation/silknet-sdl.md
          - Skia: libraries/implementation/skia.md
  - Tools:
      - Overview: tools/overview.md
      - VSCode debugger extension:
          - Debugging: tools/vscode-debugger/debugging.md
          - Development: tools/vscode-debugger/development.md
      - Remote control:
          - Overview: tools/remote-control/overview.md
          - TCP protocol: tools/remote-control/tcp-protocol.md
          - Examples: tools/remote-control/examples.md
          - Remote Client console app: tools/remote-control/remote-client.md
      - Scripting:
          - Overview: tools/scripting/overview.md
          - Configuration: tools/scripting/configuration.md
          - Lua API: tools/scripting/lua-api.md
          - Examples: tools/scripting/examples.md
  - Systems:
      - Overview: systems/overview.md
      - Adding a new system: systems/adding-a-system.md
      - C64:
          - Overview: systems/c64/overview.md
          - Libraries: systems/c64/libraries.md
          - Keyboard mapping: systems/c64/keyboard.md
          - ROMs: systems/c64/roms.md
          - SwiftLink support: systems/c64/swiftlink.md
          - Basic code completion: systems/c64/code-completion.md
          - Compatible programs: systems/c64/compatible-programs.md
          - Useful tools: systems/c64/useful-tools.md
      - Generic:
          - Overview: systems/generic/overview.md
          - Libraries: systems/generic/libraries.md
      - VIC-20:
          - Overview: systems/vic20/overview.md
          - Libraries: systems/vic20/libraries.md
          - ROMs: systems/vic20/roms.md
