using Highbyte.DotNet6502;
using Highbyte.DotNet6502.Systems.Generic;
using Highbyte.DotNet6502.Systems.Generic.Config;
using Highbyte.DotNet6502.Systems.Snapshots;
using Highbyte.DotNet6502.Utils;
using Microsoft.Extensions.Logging.Abstractions;

namespace Highbyte.DotNet6502.Systems.Tests.Snapshots;

/// <summary>
/// CPU model identity in snapshots: the cpu-6502
/// module (v2) records which CPU model the state was captured on; restoring onto a
/// different model is a hard error; v1 payloads (captured before CPU models existed)
/// restore as nmos6502 — proven against a checked-in fixture written by the REAL v1
/// writer, not regenerated by current code.
/// </summary>
public class CpuModelSnapshotTests
{
    private static GenericComputer BuildComputer(string cpuModelId = CpuModelIds.Nmos6502)
    {
        var config = new GenericComputerConfig
        {
            CpuModelId = cpuModelId,
            CpuCompatibilityProfile = cpuModelId == CpuModelIds.Ncr65c02
                ? CpuCompatibilityProfile.OfficialOnly
                : CpuCompatibilityProfile.ExperimentalUnofficial,
        };
        var computer = new GenericComputer(config, new NullLoggerFactory());
        // Same tiny program as the generic round-trip tests: observable state changes.
        computer.Mem.StoreData(0xC000, new byte[] { 0xA9, 0x05, 0x8D, 0x00, 0x20, 0xE8, 0xC8, 0x4C, 0x05, 0xC0 });
        computer.CPU.PC = 0xC000;
        return computer;
    }

    [Fact]
    public void Restoring_Onto_A_Different_Cpu_Model_Is_A_Hard_Error()
    {
        var source = BuildComputer(CpuModelIds.Nmos6502);
        for (int i = 0; i < 5; i++)
            source.ExecuteOneInstruction(out _);

        using var snapshotStream = new MemoryStream();
        new SnapshotService().Save(source, snapshotStream);
        snapshotStream.Position = 0;

        var target65c02 = BuildComputer(CpuModelIds.Ncr65c02);
        var targetPcBefore = target65c02.CPU.PC;

        var ex = Assert.Throws<SnapshotIncompatibleException>(
            () => new SnapshotService().Restore(target65c02, snapshotStream));
        Assert.Contains("nmos6502", ex.Message);
        Assert.Contains("ncr65c02", ex.Message);
        // Rejected before any CPU state was applied.
        Assert.Equal(targetPcBefore, target65c02.CPU.PC);
    }

    [Fact]
    public void Restoring_65c02_Snapshot_Onto_Nmos_Is_Also_A_Hard_Error()
    {
        var source = BuildComputer(CpuModelIds.Ncr65c02);
        for (int i = 0; i < 5; i++)
            source.ExecuteOneInstruction(out _);

        using var snapshotStream = new MemoryStream();
        new SnapshotService().Save(source, snapshotStream);
        snapshotStream.Position = 0;

        var targetNmos = BuildComputer(CpuModelIds.Nmos6502);
        Assert.Throws<SnapshotIncompatibleException>(
            () => new SnapshotService().Restore(targetNmos, snapshotStream));
    }

    [Fact]
    public void Matching_65c02_Model_Round_Trips_Successfully()
    {
        var source = BuildComputer(CpuModelIds.Ncr65c02);
        for (int i = 0; i < 5; i++)
            source.ExecuteOneInstruction(out _);

        using var snapshotStream = new MemoryStream();
        new SnapshotService().Save(source, snapshotStream);
        snapshotStream.Position = 0;

        var restored = BuildComputer(CpuModelIds.Ncr65c02);
        restored.CPU.PC = 0x0000;
        var result = new SnapshotService().Restore(restored, snapshotStream);

        Assert.Equal(source.CPU.PC, restored.CPU.PC);
        Assert.Equal(3, result.Manifest.Modules.First(m => m.Name == Cpu6502SnapshotModule.ModuleName).Version);
    }

    [Fact]
    public void Nmos6502_Snapshot_Restores_Onto_A_Mos6510_Target()
    {
        // The 6510 is an NMOS 6502 core with an added I/O port: cpu-6502 state transfers
        // exactly. This is what lets C64 snapshots captured before the C64 switched to
        // the mos6510 model id keep restoring.
        var source = BuildComputer(CpuModelIds.Nmos6502);
        for (int i = 0; i < 5; i++)
            source.ExecuteOneInstruction(out _);

        using var snapshotStream = new MemoryStream();
        new SnapshotService().Save(source, snapshotStream);
        snapshotStream.Position = 0;

        var target6510 = BuildComputer(CpuModelIds.Mos6510);
        target6510.CPU.PC = 0x0000;
        new SnapshotService().Restore(target6510, snapshotStream);

        Assert.Equal(source.CPU.PC, target6510.CPU.PC);
        Assert.Equal(source.CPU.A, target6510.CPU.A);
    }

    [Fact]
    public void Mos6510_Snapshot_Restores_Onto_An_Nmos6502_Target()
    {
        var source = BuildComputer(CpuModelIds.Mos6510);
        for (int i = 0; i < 5; i++)
            source.ExecuteOneInstruction(out _);

        using var snapshotStream = new MemoryStream();
        new SnapshotService().Save(source, snapshotStream);
        snapshotStream.Position = 0;

        var targetNmos = BuildComputer(CpuModelIds.Nmos6502);
        targetNmos.CPU.PC = 0x0000;
        new SnapshotService().Restore(targetNmos, snapshotStream);

        Assert.Equal(source.CPU.PC, targetNmos.CPU.PC);
    }

    [Fact]
    public void Mos6510_Snapshot_Onto_A_65c02_Is_Still_A_Hard_Error()
    {
        var source = BuildComputer(CpuModelIds.Mos6510);
        for (int i = 0; i < 5; i++)
            source.ExecuteOneInstruction(out _);

        using var snapshotStream = new MemoryStream();
        new SnapshotService().Save(source, snapshotStream);
        snapshotStream.Position = 0;

        var target65c02 = BuildComputer(CpuModelIds.Ncr65c02);
        Assert.Throws<SnapshotIncompatibleException>(
            () => new SnapshotService().Restore(target65c02, snapshotStream));
    }

    [Fact]
    public void Mos6510_Port_State_Round_Trips_Through_The_Cpu_Module()
    {
        // v3 capability: model state persists with the CPU. Before this the Generic
        // system silently lost the 6510's port registers on snapshot.
        var source = BuildComputer(CpuModelIds.Mos6510);
        ((Cpu6510Port)source.CPU.ModelState!).SetState(dataDirectionRegister: 0x2F, dataRegister: 0x35);

        using var snapshotStream = new MemoryStream();
        new SnapshotService().Save(source, snapshotStream);
        snapshotStream.Position = 0;

        var restored = BuildComputer(CpuModelIds.Mos6510);
        var restoredPort = (Cpu6510Port)restored.CPU.ModelState!;
        Assert.NotEqual(0x35, restoredPort.DataRegister);

        new SnapshotService().Restore(restored, snapshotStream);

        Assert.Equal(0x2F, restoredPort.DataDirectionRegister);
        Assert.Equal(0x35, restoredPort.DataRegister);
    }

    [Fact]
    public void Mos6510_Port_Restore_Notifies_Once_With_Final_State()
    {
        var source = BuildComputer(CpuModelIds.Mos6510);
        ((Cpu6510Port)source.CPU.ModelState!).SetState(0x2F, 0x35);

        using var snapshotStream = new MemoryStream();
        new SnapshotService().Save(source, snapshotStream);
        snapshotStream.Position = 0;

        var restored = BuildComputer(CpuModelIds.Mos6510);
        var restoredPort = (Cpu6510Port)restored.CPU.ModelState!;
        var notifications = 0;
        (byte Ddr, byte Data) seen = default;
        restoredPort.OutputsChanged += () =>
        {
            notifications++;
            seen = (restoredPort.DataDirectionRegister, restoredPort.DataRegister);
        };

        new SnapshotService().Restore(restored, snapshotStream);

        Assert.Equal(1, notifications);
        Assert.Equal((0x2F, 0x35), seen);
    }

    [Fact]
    public void Mos6510_Payload_Onto_Nmos6502_Target_Warns_And_Ignores_The_Port()
    {
        var source = BuildComputer(CpuModelIds.Mos6510);
        ((Cpu6510Port)source.CPU.ModelState!).SetState(0x2F, 0x35);
        for (int i = 0; i < 5; i++)
            source.ExecuteOneInstruction(out _);

        using var snapshotStream = new MemoryStream();
        new SnapshotService().Save(source, snapshotStream);
        snapshotStream.Position = 0;

        var targetNmos = BuildComputer(CpuModelIds.Nmos6502);
        var result = new SnapshotService().Restore(targetNmos, snapshotStream);

        // Core state restored; the port payload is warned about and skipped.
        Assert.Equal(source.CPU.PC, targetNmos.CPU.PC);
        Assert.Contains(result.Warnings, w => w.Contains("model-state payload"));
    }

    [Fact]
    public void Nmos6502_Snapshot_Onto_Mos6510_Target_Warns_That_The_Port_Keeps_Its_Values()
    {
        var source = BuildComputer(CpuModelIds.Nmos6502);
        for (int i = 0; i < 5; i++)
            source.ExecuteOneInstruction(out _);

        using var snapshotStream = new MemoryStream();
        new SnapshotService().Save(source, snapshotStream);
        snapshotStream.Position = 0;

        var target6510 = BuildComputer(CpuModelIds.Mos6510);
        ((Cpu6510Port)target6510.CPU.ModelState!).SetState(0x2F, 0x37);
        var result = new SnapshotService().Restore(target6510, snapshotStream);

        Assert.Equal(source.CPU.PC, target6510.CPU.PC);
        Assert.Equal(0x37, ((Cpu6510Port)target6510.CPU.ModelState!).DataRegister); // untouched
        Assert.Contains(result.Warnings, w => w.Contains("no model-state payload"));
    }

    [Fact]
    public void V1_Fixture_Captured_Before_Cpu_Models_Restores_As_Nmos6502()
    {
        // The fixture was written by the actual v1 module code (before the model id
        // existed in the payload) and is checked in — NOT regenerated by current code.
        var fixturePath = Path.Combine(AppContext.BaseDirectory, "Snapshots", "Fixtures", "generic-cpu6502-v1.d6502snap");
        Assert.True(File.Exists(fixturePath), $"Missing fixture: {fixturePath}");

        using var fixtureStream = File.OpenRead(fixturePath);
        var target = BuildComputer(CpuModelIds.Nmos6502);
        target.CPU.PC = 0x0000;

        var result = new SnapshotService().Restore(target, fixtureStream);

        // v1 restores fine onto the (implied) nmos6502 model; state applied.
        Assert.Equal(1, result.Manifest.Modules.First(m => m.Name == Cpu6502SnapshotModule.ModuleName).Version);
        Assert.NotEqual(0, target.CPU.PC);
        Assert.Equal((byte)0x05, target.Mem[0x2000]); // program had run before capture
    }

    [Fact]
    public void V1_Fixture_Restored_Onto_A_65c02_Is_A_Hard_Error()
    {
        var fixturePath = Path.Combine(AppContext.BaseDirectory, "Snapshots", "Fixtures", "generic-cpu6502-v1.d6502snap");
        using var fixtureStream = File.OpenRead(fixturePath);
        var target65c02 = BuildComputer(CpuModelIds.Ncr65c02);

        // A v1 snapshot is implicitly nmos6502 state — restoring it onto a 65C02 machine
        // must hard-reject just like an explicit model mismatch.
        Assert.Throws<SnapshotIncompatibleException>(
            () => new SnapshotService().Restore(target65c02, fixtureStream));
    }
}
