namespace SadConsoleTest
{
    public class SadConsoleConfig
    {
        public string WindowTitle { get; set; }
        public int FontScale { get; set; }
        public SadConsoleConfig()
        {
            WindowTitle = "SadConsole displaying screen generated by machine code running in Highbyte.DotNet6502 emulator.";
            FontScale = 1;
        }
    }
}
