<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Highbyte.DotNet6502.App.Avalonia.Core\Highbyte.DotNet6502.App.Avalonia.Core.csproj" />
    <ProjectReference Include="..\..\..\libraries\Highbyte.DotNet6502.Systems.Oric\Highbyte.DotNet6502.Systems.Oric.csproj" />
    <ProjectReference Include="..\..\..\libraries\Highbyte.DotNet6502.Systems.Plugins\Highbyte.DotNet6502.Systems.Plugins.csproj" />
    <ProjectReference Include="..\..\..\libraries\Highbyte.DotNet6502.Impl.Avalonia.Oric\Highbyte.DotNet6502.Impl.Avalonia.Oric.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Views\OricConfigDialogView.axaml.cs"><DependentUpon>OricConfigDialogView.axaml</DependentUpon></Compile>
    <Compile Update="Views\OricConfigDialog.axaml.cs"><DependentUpon>OricConfigDialog.axaml</DependentUpon></Compile>
    <Compile Update="Views\OricInfoView.axaml.cs"><DependentUpon>OricInfoView.axaml</DependentUpon></Compile>
    <Compile Update="Views\OricMenuView.axaml.cs"><DependentUpon>OricMenuView.axaml</DependentUpon></Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\..\..\samples\Assembler\Oric\Raster\Build\*.tap">
      <Link>Resources\Sample6502Programs\Assembler\Oric\%(Filename)%(Extension)</Link>
      <LogicalName>$(AssemblyName).Resources.Sample6502Programs.Assembler.Oric.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\..\samples\Basic\Oric\Text\Build\*.tap">
      <Link>Resources\Sample6502Programs\Basic\Oric\%(Filename)%(Extension)</Link>
      <LogicalName>$(AssemblyName).Resources.Sample6502Programs.Basic.Oric.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
