namespace Highbyte.DotNet6502.SadConsoleHost
{
    public class SadConsoleConfig
    {
        public string WindowTitle { get; set; }

        /// <summary>
        /// Optional. If not specified, default SadConsole font is used.
        /// To use a specific  SadConsole Font, include it in your program output directory.
        /// Example: Fonts/C64.font
        /// </summary>
        /// <value></value>
        public string Font { get; set; }
        /// <summary>
        /// Font scale. 1 is default.
        /// </summary>
        /// <value></value>
        public int FontScale { get; set; }
        public SadConsoleConfig()
        {
            WindowTitle = "SadConsole displaying screen generated by machine code running in Highbyte.DotNet6502 emulator.";
            Font = null;
            FontScale = 1;           
        }
    }
}
